version: '3'

volumes:
  local_postgres_data: {}

services:
  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    image: cpims_django
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./docker/django/.django
      - ./docker/postgres/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    image: cpims_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./docker/postgres/.postgres

  