# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpovc_forms', '0007_auto_20190305_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ovccarebenchmarkscore',
            old_name='care_giver_id',
            new_name='care_giver',
        ),
        migrations.RenameField(
            model_name='ovccarebenchmarkscore',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='ovccarebenchmarkscore',
            old_name='household_id',
            new_name='household',
        ),
        migrations.RenameField(
            model_name='ovccarecaseplan',
            old_name='cp_service_id',
            new_name='cp_service',
        ),
        migrations.RenameField(
            model_name='ovccarecaseplan',
            old_name='person_id',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='ovccarecpara',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='ovccarecpara',
            old_name='household_id',
            new_name='household',
        ),
        migrations.RenameField(
            model_name='ovccarecpara',
            old_name='person_id',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='ovccarewellbeing',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='ovccarewellbeing',
            old_name='household_id',
            new_name='household',
        ),
        migrations.RenameField(
            model_name='ovccarewellbeing',
            old_name='person_id',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='ovchivstatus',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='ovchivstatus',
            old_name='person_id',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='ovchouseholddemographics',
            old_name='household_id',
            new_name='household',
        ),
        migrations.RenameField(
            model_name='ovcmonitoring',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='ovcmonitoring',
            old_name='household_id',
            new_name='household',
        ),
        migrations.RenameField(
            model_name='ovcreferrals',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='ovcreferrals',
            old_name='person_id',
            new_name='person',
        ),
        migrations.RemoveField(
            model_name='ovchivstatus',
            name='date_1',
        ),
        migrations.AddField(
            model_name='ovccarecpara',
            name='question',
            field=models.ForeignKey(to='cpovc_forms.OVCCareQuestions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ovccarewellbeing',
            name='question',
            field=models.ForeignKey(to='cpovc_forms.OVCCareQuestions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ovcexplanations',
            name='question',
            field=models.ForeignKey(to='cpovc_forms.OVCCareQuestions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ovcmonitoring',
            name='quarter',
            field=models.CharField(max_length=10),
            preserve_default=False,
        ),
    ]
